export default {
    globals: `
        font-family: var(--sans);
        -webkit-font-smoothing: antialiased;
        text-rendering: geometricPrecision;
        -webkit-tap-highlight-color: transparent;
        font-size: var(--lumi-unit);
        background-color: var(--lumi-background);
        color: var(--lumi-foreground);
        margin: 0;
        padding: 0;
    `,
    variables: {
        "sans": '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
        "mono": 'Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace',
        "scale": 0.5,
        "lumi-columns": 12,
        "lumi-gap": {
            "xs": "4px",
            "sm": "8px",
            "md": "16px",
        },
        "lumi-unit": "16px",
        "lumi-unit-half": "calc(var(--lumi-unit) / 2)",
        "lumi-unit-quarter": "calc(var(--lumi-unit) / 4)",
        "xs": "650px",
        "sm": "900px",
        "md": "1280px",
        "lg": "1920px",

        "lumi-avatar-size": {
            "xs": "48px",
            "sm": "48px",
            "md": "48px",
            "lg": "64px",
        },
        "lumi-background": "#fff",
        "lumi-text-color": "#000",
        "lumi-text-color-contrast": "#fff",
        "lumi-accents-1": "#fafafa",
        "lumi-accents-2": "#eaeaea",
        "lumi-accents-3": "#999",
        "lumi-accents-4": "#888",
        "lumi-accents-5": "#666",
        "lumi-accents-6": "#444",
        "lumi-accents-7": "#333",
        "lumi-accents-8": "#111",
        "lumi-foreground": "#000",
        "lumi-error-lighter": "#f7d4d6",
        "lumi-error-light": "#ff1a1a",
        "lumi-error": "#e00",
        "lumi-error-dark": "#c50000",
        "lumi-success-lighter": "#d3e5ff",
        "lumi-success-light": "#3291ff",
        "lumi-success": "#0070f3",
        "lumi-success-dark": "#0761d1",
        "lumi-warning-lighter": "#ffefcf",
        "lumi-warning-light": "#f7b955",
        "lumi-warning": "#f5a623",
        "lumi-warning-dark": "#ab570a",
        "lumi-violet-lighter": "#d8ccf1",
        "lumi-violet-light": "#8a63d2",
        "lumi-violet": "#7928ca",
        "lumi-violet-dark": "#4c2889",
        "lumi-red-light": "#ff1a1a",
        "lumi-red": "#e00",
        "lumi-red-dark": "#c50000",
        "lumi-yellow": "#fff500",
        "lumi-orange-light": "#f7b955",
        "lumi-orange-dark": "#ab570a",
        "lumi-blue-light": "#3291ff",
        "lumi-blue": "#0070f3",
        "lumi-blue-dark": "#0761d1",
        "lumi-cyan-lighter": "#aaffec",
        "lumi-cyan-light": "#79ffe1",
        "lumi-cyan": "#50e3c2",
        "lumi-cyan-dark": "#29bc9b",

        "lumi-background-hover": "#fafafa",
        "lumi-border-active-color": "var(--lumi-accents-3)",
        "lumi-background-hover-active": "#cce6ff",

        "lumi-highlight-purple": "#f81ce5",
        "lumi-highlight-magenta": "#eb367f",
        "lumi-highlight-pink": "#ff0080",
        "lumi-highlight-yellow": "#fff500",
        "lumi-border-radius": "5px",
        "lumi-border": "1px solid var(--lumi-accents-2)",
        "lumi-focus-color": "var(--lumi-success)",
        "lumi-outline": "2px solid var(--lumi-focus-color)",
        "lumi-shadow-border": "0 0 0 1px rgba(0,0,0,.08)",
        "lumi-shadow-border-active": "0 0 0 1px rgba(0,0,0,.16)",
        "lumi-shadow-small": "0 2px 2px rgba(0,0,0,.04)",
        "lumi-shadow-border-small": "var(--lumi-shadow-border),var(--lumi-shadow-small)",
        "lumi-shadow-medium": "0px 2px 2px rgba(0,0,0,.04),0px 8px 8px -8px rgba(0,0,0,.04)",
        "lumi-shadow-border-medium": "var(--lumi-shadow-border),var(--lumi-shadow-medium)",
        "lumi-shadow-large": "0px 2px 2px rgba(0,0,0,.04),0px 8px 16px -4px rgba(0,0,0,.04)",
        "lumi-shadow-border-large": "var(--lumi-shadow-border),var(--lumi-shadow-large)",
        "lumi-shadow-tooltip": "var(--lumi-shadow-border),0px 1px 1px rgba(0,0,0,.02),0px 4px 8px rgba(0,0,0,.04)",
        "lumi-shadow-menu": "var(--lumi-shadow-border),0px 1px 1px rgba(0,0,0,.02),0px 4px 8px -4px rgba(0,0,0,.04),0px 16px 24px -8px rgba(0,0,0,.06)",
        "lumi-shadow-modal": "var(--lumi-shadow-border),0px 1px 1px rgba(0,0,0,.02),0px 8px 16px -4px rgba(0,0,0,.04),0px 24px 32px -8px rgba(0,0,0,.06)",
        "lumi-shadow-fullscreen": "var(--lumi-shadow-border),0px 1px 1px rgba(0,0,0,.02),0px 8px 16px -4px rgba(0,0,0,.04),0px 24px 32px -8px rgba(0,0,0,.06)",
        "lumi-focus-ring": "0 0 0 2px var(--lumi-background),0 0 0 4px var(--lumi-focus-color)",
        "lumi-icon-size": "calc(var(--lumi-unit)*1.5)",
        "lumi-card-padding": "var(--lumi-gap)",

        "lumi-background-transition": "background .15s ease,border .15s ease",

    }
};